### ISSUE TITLE
I can't ban players who play on the bedrock version.

### ISSUE THREAD

**Issue by thiagogebrim13** [Baktus79/BanFromClaim#11]
The bug happens due to my server being java and having players with bedrock, I use in bedrock players a prefix ".", and it seems to be a UUID error that it doesn't recognize..
![image](https://user-images.githubusercontent.com/75040244/124317349-68136b80-db4d-11eb-82b6-bf59eeb6ee2e.png)

**BanFromClaim most new**
**1.17 purpur**

**Comment by Baktus79** [comment]
Hi, unfortunately this plugin is not designed for use with Bedrock players. The reason for this is that Bedrock users do not have UUID, and that creates a problem. Yes, it is true that these users get fake UUID numbers on the server, but still they are not completely valid.
