### ISSUE TITLE
[Bug] Player get stuck if banned when inside claim

### ISSUE THREAD

**Issue by giantfurkii** [Baktus79/BanFromClaim#14]
**Describe the bug**

https://user-images.githubusercontent.com/78488589/140015130-7a8003fd-b559-429c-a414-d028fc09b5fa.mp4

When the player was banned while in the claim, the claim also stuck.

---

**ERROR MESSAGE**
```
## Replace me with the error message ##
```

---

**Additional server information**

**BanFromClaim version: 1.5.11**
**Server version (use /ver):airplane - 95**
**Plugin list:**

**Comment by Baktus79** [comment]
I have recreated this error and it will be fixed on the next release.

**Comment by austv** [comment]
@Baktus79 Hey, I having this same issue in the new version, 1.6.2
I'm running purpur 1.18.2

**Comment by Baktus79** [comment]
@austv Are you using GriefPrevention?

**Comment by austv** [comment]
@Baktus79 Yes, GriefPrevention version 16.18-RC1-15-gb83e363
