### ISSUE TITLE
[Request] Bypass permission

### ISSUE THREAD

**Issue by Grafhugo** [Baktus79/BanFromClaim#15]
**Describe your request for a new feature or improvement**
Hello,

i would suggest a kinda bypass like with gamemode 3 (spectator)

Thanks ^^

**Comment by Baktus79** [comment]
Hi,

There is such a permission node already available on BanFromClaim. See [https://github.com/Baktus79/BanFromClaim/wiki/Permissions](https://github.com/Baktus79/BanFromClaim/wiki/Permissions) for more information on permissions.

The bypass permission:
`bfc.bypass`

About the gamemode 3 feature, yes, they should definitely not be banned from a claim. I'll look into it.

**Comment by Baktus79** [comment]
I have now implemented bypass by spectate. This will be available at the next release.
