### ISSUE TITLE
[Bug] BFC Invalid Player Name

### ISSUE THREAD

**Issue by imlaptev** [Baktus79/BanFromClaim#17]
**Describe the bug**
Hello!

When I use the command /bfc (to ban a player from my claim) on my server, it says that '[Username] is not a valid player name. 

Ex; /bfc Notch :: Notch is not a valid player name.

---

**ERROR MESSAGE**
```
[Username] is not a valid player name.
```

---

**Additional server information**

**BanFromClaim version:**
**Server version (use /ver):**
"Failed to retrieve version from server." 1.17.1
**Plugin list:**

**Comment by Baktus79** [comment]
You can not ban players who have not connected to your server.

**Comment by imlaptev** [comment]
They had joined at this point. That is the error.

**Comment by Baktus79** [comment]
So far, I have not been able to reproduce the problem you are experiencing. If the server failed to display the version number then it seems that things are very wrong on your server, or that you are using a server that is not supported by BFC.
