### ISSUE TITLE
[Bug] GriefPrevention not allowing for Bedrock (GeyserMC) Players to be kicked

### ISSUE THREAD

**Issue by JasmineWMCM** [Baktus79/BanFromClaim#22]
**Describe the bug**

---

**ERROR MESSAGE**
```
N/A
```

---

**Additional server information**

**BanFromClaim version:** 1.5.11
**Server version (use /ver):** SolarSpigot (Custom Made Spigot) 1.17.1
**Plugin list:** 97

**Comment by Baktus79** [comment]
Yes, this is true if you allow Bedrock user accounts on your server. Bedrock user accounts work differently than Java user accounts, and therefore BFC will not recognize the user. If I'm not completely wrong, Bedrock users need to be converted to a Java user, but this Java user will be different every time they connect to your server.

**Comment by JasmineWMCM** [comment]
Would it be possible if you recognize their UUID then?

**Comment by Baktus79** [comment]
I am really not sure, but I think they will have different UUID from each time. If the UUID was the same they should have been banned from the claim because the plugin is heavily depended on UUIDs.

**Comment by JasmineWMCM** [comment]
I think it's the same each time

**Comment by Baktus79** [comment]
I have no Bedrock user I can check this theory with. Is this something you can confirm?

**Comment by Baktus79** [comment]
I did find this on the GeyserMC website:

> **How do I include players in commands when using Floodgate?**
If there is a prefix on Floodgate players, you must include the prefix in the name. Floodgate also replaces all spaces in names with underscores, so be sure to replace any spaces with underscores when executing the command. If this does not work, put double quotes around the name. 
Example: /tp ".<bedrock_username>"

And yes, you were right about fixed UUID, but despite this, there are still many things that do not work with GeyserMC / Floodgate. It is not compatible enough with Java servers.
