### ISSUE TITLE
[Request]Multiple translations

### ISSUE THREAD

**Issue by xaprier** [Baktus79/BanFromClaim#25]
I added messages.yml file which translated to Turkish for this plugin to my https://github.com/xaprier/gaiacraft-minecraft repo.

You can maybe create multiple translations file or not. I want you to know this.

The dir is Plugins/BanFromClaim/
And the "Tapu" word means land register in Turkish. Maybe you can add prefix setting to messages.yml file.

**Comment by Baktus79** [comment]
Thanks, I'll be sure to use your translation if I ever add support for this.
