### ISSUE TITLE
Cant ban player from claim doesnt recognize player names

### ISSUE THREAD

**Issue by MindMasterz** [Baktus79/BanFromClaim#27]
The command /banfromclaim doesnt work to ban individual players it wont read their names. the kick and banall command work but the individual ban is the most beneficial. thansk for any help
![2022-10-09_14 02 59](https://user-images.githubusercontent.com/108431965/194774974-5457aabb-1e97-48bb-ac8e-c38ca40d2b9b.png)

**Comment by Baktus79** [comment]
Fixed on next release
