### ISSUE TITLE
[Bug] Bypass ban with water

### ISSUE THREAD

**Issue by MrSwalbert** [Baktus79/BanFromClaim#34]
**Describe the bug**
When a player is banned from a claim, if they place water down and are moved into a claim that they are banned from, they will be able to enter the claim and bypass the ban.

---

**ERROR MESSAGE**
```
No error message.
```

---

**Additional server information**

**BanFromClaim version:** 1.6.5
**Server version (use /ver):** 1.20.1

**Comment by Baktus79** [comment]
Could not reproduce this, could you give me more specifics?
