### ISSUE TITLE
[Bug] Bypass ban with Gsit

### ISSUE THREAD

**Issue by thechosecat** [Baktus79/BanFromClaim#35]
**Describe the bug**
When a player sitting on the other player(im useing Gsit Plugin)
https://www.spigotmc.org/resources/gsit-modern-sit-seat-and-chair-lay-and-crawl-plugin-1-13-1-20.62325/
both player can pass bfcall and move in claim

**ERROR MESSAGE**
no
---

**Additional server information**

**BanFromClaim version:1.6.5**
**Server version (use /ver): paper 1.20.1 git 68**
**Plugin list: BanFromClaim Griefprevention Gsit**

**Comment by thechosecat** [comment]
Hello, I have created a simple patch to fix this issue. Please approve my pull request :D

**Comment by Baktus79** [comment]
Thanks for the pull request. I'll take a look at your suggestion :)

**Comment by Baktus79** [comment]
This is fixed in the new release.
