### ISSUE TITLE
[Bug] That kills a server

### ISSUE THREAD

**Issue by SinistersGrin** [Baktus79/BanFromClaim#36]
**Describe the bug**
If you are in a boat inside a claim and get banned it wont kick you from the claim, and if you drive the boat towards the edge of the claim and keep doing it, it ends up killing the tps which eventually crashes a server.

---

**ERROR MESSAGE**
```
There aren't any
```

---

Paper Server Version is 1.20.1 Build 196

**BanFromClaim version:** BanFromClaim 1.6.5
**Server version (use /ver):**  This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-183 (MC: 1.20.1)
**Plugin list:** There are 111 plugins, none relevant to this aside from it and GriefPrevention

**Comment by Baktus79** [comment]
I'll do some testing with boats. Thanks for your feedback!

**Comment by Baktus79** [comment]
I have now attempted this, but I am unable to reproduce the problem you are experiencing with boats.
