### ISSUE TITLE
[Bug] 1.6.6 /bfcall bans the claim owner

### ISSUE THREAD

**Issue by MrRockis** [Baktus79/BanFromClaim#39]
**Describe the bug**
Newest version 1.6.6 prevents claim owners from entering their own claim if they have /bfcall enabled. Also if they enable it whilst inside the claim, they get teleported away.

This bug is not present in the 1.6.5 version.

---

**ERROR MESSAGE**
```
## No error message ##
```

---

**Additional server information**

**BanFromClaim version:** 1.6.6
**Server version (use /ver):** 1.20.2
**Plugin list:** not applicable

**Comment by Baktus79** [comment]
Have you tested the new file I uploaded on SpigotMC?

**Comment by MrRockis** [comment]
Yes, this happens on the [1.6.6 Corrupt file](https://www.spigotmc.org/resources/banfromclaim.70897/update?update=533953) update as well.

**Comment by Baktus79** [comment]
Try this one https://github.com/Baktus79/BanFromClaim/releases/tag/1.6.6

**Comment by HorusApl** [comment]
Can confirm having this issue as well.

**Comment by Baktus79** [comment]
Have you tried the new compiled jar file from the link above?

**Comment by HorusApl** [comment]
Will give that a try.

**Comment by MrRockis** [comment]
Seems like this build fixed this issue for me.
