### ISSUE TITLE
[Request] Really need a way to make banning safe.

### ISSUE THREAD

**Issue by CrispyDairy** [Baktus79/BanFromClaim#5]
**Describe your request for a new feature or improvement**

The plugin doesn't check where it places banned players and I'm having some major issues because of that. People falling into the void in the end, which gives my staff team way too much work.

**Comment by Baktus79** [comment]
I will look into this! Thank you for reporting!

**Comment by CrispyDairy** [comment]
Thanks a lot, otherwise the plugin is great. It's just annoying that people
can essentially make traps like that. You could also look into making a
hook for the plugin Player warps, that way people don't warp into claims
they're banned from :)

su 25. huhtik. 2021 klo 18.08 Baktus79 ***@***.***) kirjoitti:

**Comment by Baktus79** [comment]
I have thought of a solution that I think will be for the best. I set up an option for servers to set up a shared safe spot. Whether it is in spawn or in another suitable place is up to the server.

**Comment by Baktus79** [comment]
BanFromClaim v1.5.4 has been released with your suggestion.
https://github.com/Baktus79/BanFromClaim/releases/tag/1.5.4
