### ISSUE TITLE
[Bug] TPS Lag caused by me.ryanhamshire.GriefPrevention.DataStore.getClaim()

### ISSUE THREAD

**Issue by DarkChromaMC** [Baktus79/BanFromClaim#50]
**Describe the bug**
We are experiencing significant server lag (8%) of tick at higher player counts. It seems to specifically come from me.ryanhamshire.GriefPrevention.DataStore.getClaim() method.
https://spark.lucko.me/0oIUisWjFY

---

**ERROR MESSAGE**
```
## Replace me with the error message ##
```

---

**Additional server information**
GriefPrevention version: 16.18.4
**BanFromClaim version:** 1.7.4
**Server version (use /ver):** 1.21.1
**Plugin list:**

**Comment by DarkChromaMC** [comment]
The plugin appears to be checking if the player is in a claim from which they have been banned in a roundabout way. Could we please use `DataStore#getClaimAt` instead of `DataStore#getClaim`?

**Comment by Baktus79** [comment]
I'm not sure how `DataStore#getClaimAt`should be more efficient than  `DataStore#getClaim`. But I will look into it to see if there is any difference between those two.

**Comment by DarkChromaMC** [comment]
It seems another plugin (GPFlags), also reported this issue a couple weeks ago, and pushed a fix to change to `DataStore#getClaimAt`. Here's the GitHub report discussion about it: https://github.com/GriefPrevention/GriefPrevention/issues/2249

**Comment by Baktus79** [comment]
Got some info about the issue from RoboMWM, `DataStore#getClaimAt` operates much different than `DataStore#getClaim`. As it only gets a subset of claims based on the chunk, rather than all claims, and that the search is in a hashmap makes it more efficient.

I will change it within the next release.
