### ISSUE TITLE
[Feature] Console spam

### ISSUE THREAD

**Issue by jurohn** [Baktus79/BanFromClaim#54]
**Describe the bug**
I want to make this message in the console toggelable. Can you make a config option with:

Display console message: y/n?

[BanFromClaim] The database has been purged of expired **regions**
is displayed every hour and i wish to get rid of this.

Or at least that i have the choice to get rid of it!

**Comment by Baktus79** [comment]
I might remove that feature all together as it might not be needed. I will work on BanFromClaim within the next two weeks. Next update will remove the message either way.

**Comment by jurohn** [comment]
> I might remove that feature all together as it might not be needed. I will work on BanFromClaim within the next two weeks. Next update will remove the message either way.

Thank you!

**Comment by Baktus79** [comment]
I removed the entire procedure to check for expired regions, therefore the message will no longer appear in the console. I have replaced the procedure with something that only removes when necessary. Saves resources and performance.

The new release is out now.

**Comment by jurohn** [comment]
> I removed the entire procedure to check for expired regions, therefore the message will no longer appear in the console. I have replaced the procedure with something that only removes when necessary. Saves resources and performance.
> 
> The new release is out now.

Thank you very much!
