### ISSUE TITLE
Should be thrown away from the claim

### ISSUE THREAD

**Issue by eretna123** [Baktus79/BanFromClaim#8]
**Describe the bug**
If player using claimban other player teleporting to the end of the claim and still staying in claim. People using tpa trap.  
Instead of throwing it to the end of the claim, must be thrown away from the claim. Sorry for my bad english.

---

**ERROR MESSAGE**
```
## Replace me with the error message ##
```

---

**Additional server information**
1.16.5 Latest Airplane

**BanFromClaim version:**
1.5.5
**Server version (use /ver):**
1.16.5
**Plugin list:**

**Comment by Baktus79** [comment]
This will be fixed on the next release.
